checkoutLocation: src/github.com/vanHeemstraSystems/native-app-in-gitpod
workspaceLocation: /
image:
  file: Dockerfile
ports:
  - port: 6080
    protocol: "http"
tasks:
  - command: "go install -v ./... && go run main.go"
